"""
main.py
-------
TalentLens API — FastAPI entrypoint.

This replaces the old Streamlit app.py entirely. All parsing/scoring/
chatbot logic is unchanged (moved into app/services/) — this file only
wires it up as HTTP endpoints, adds CORS for the separate frontend, and
exposes a health check for deployment platforms.

Run locally:   uvicorn app.main:app --reload
Docs:          http://localhost:8000/docs  (auto-generated by FastAPI)
"""

from typing import Optional
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.core.config import get_settings
from app.db.models import HealthResponse
from app.routers import candidates, rankings, chat, auth, notifications, ats, gmail, interview
from dotenv import load_dotenv
load_dotenv()

settings = get_settings()

app = FastAPI(
    title="TalentLens API",
    description="AI-powered resume screening & candidate ranking — backend API.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(RuntimeError)
async def runtime_error_handler(request: Request, exc: RuntimeError):
    """Turns configuration errors (e.g. missing Supabase env vars) into a
    clean 503 response instead of an opaque 500, so misconfiguration is
    obvious to whoever is testing the API."""
    return JSONResponse(status_code=503, content={"detail": str(exc)})


app.include_router(auth.router)
app.include_router(notifications.router)
app.include_router(ats.router)
app.include_router(gmail.router)
app.include_router(interview.router)

app.include_router(candidates.router)
app.include_router(rankings.router)
app.include_router(chat.router)


@app.get("/", tags=["Meta"])
def root(request: Request, code: Optional[str] = None, state: Optional[str] = None):
    """Root endpoint.

    Normally returns API metadata — but if Google bounces an OAuth callback
    back to the bare root (i.e. the OAuth client's redirect URI is registered
    as ``http://localhost:8000`` instead of ``/gmail/auth/callback``), the
    ``code`` query param is present and we forward it to the shared Gmail
    callback handler so the connection still completes.
    """
    if code and state:
        return gmail.process_oauth_callback(request, code, state)
    return {
        "name": "TalentLens API",
        "status": "running",
        "docs": "/docs",
    }


@app.get("/health", response_model=HealthResponse, tags=["Meta"])
def health():
    """
    Deployment health check. Returns 200 even if Supabase/Groq aren't
    configured yet, but lists what's missing so misconfiguration is
    obvious immediately instead of surfacing as a mystery 500 later.
    """
    issues = settings.validate()
    return HealthResponse(
        status="ok" if not issues else "misconfigured",
        environment=settings.ENVIRONMENT,
        issues=issues,
    )
